# JWT
jwt:
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

payment:
  toss:
    secret_key: ${TOSS_SECRET_KEY}

groq:
  api-key: ${GROQ_API_KEY}
  url: ${GROQ_API_URL}

pinecone:
  api-key: ${PINECONE_API_KEY}
  url: ${PINECONE_API_URL}

langfuse:
  public-key: ${LANGFUSE_PUBLIC_KEY}
  secret-key: ${LANGFUSE_SECRET_KEY}
  url: ${LANGFUSE_BASE_URL}