server:
  port: 8881

spring:
  application:
    name: AuctionMarket

  profiles:
    active: local
    include: infra

    # 가상 스레드(성능 up / synchronized, ThreadLocal 사용 시 문제 발생)
    threads:
      virtual:
        enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}